config/routes.rb
DestroyAllTasks::Application.routes.draw do

resources :profiles, only: [:show, :edit, :update]

match 'signup', to: 'users#new', as: 'signup', via: [:get]
match 'login', to: 'sessions#new', as: 'login', via: [:get, :post]
match 'logout', to: 'sessions#destroy', as: 'logout', via: [:post]

match 'overview', to: 'pages#overview', as: 'overview', via: [:get]
match 'style-guide', to: 'pages#style_guide', as: 'style_guide', via: [:get]

match 'tags/:tags' => 'tasks#tags', as: 'tags', via: [:get]
match 'untagged' => 'tasks#untagged', as: 'untagged', via: [:get]


resources :sessions
resources :users
resources :comments

resources :tasks, except: [:new] do
  collection { post :sort }
  collection { get :punted }
  collection { post :punt_all_tagged_tasks }
  collection { post :punt_all_tasks }
  collection { put :delete_all_tagged_tasks }
end

root :to => 'pages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authorize

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
    @task = Task.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])
    @task = @comment.task_id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to task_path(@task), notice: 'Comment created.' }
        format.js { render layout: false }
      end
    else
      render action: "new"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to @comment, notice: 'Comment updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @task = @comment.task_id

    redirect_to task_path(@task)
  end

  # _dw strong params
  # :entry, :tags, :task_id, :user_id
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  = f.hidden_field :task_id, value: @task.id
  .field
    .comment-field= f.text_area :entry, rows: "5", placeholder: "Jot some notes."
  .actions.save-btn
    = f.submit 'Save', class: 'link-button-dark'

app/views/comments/create.js.erb
$('.m-task-note').slideUp();

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Entry:
  = @comment.entry
%p
  %b Tags:
  = @comment.tags

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path