config/routes.rb
DestroyAllTasks::Application.routes.draw do

resources :profiles, only: [:show, :edit, :update]

match 'signup', to: 'users#new', as: 'signup', via: [:get]
match 'login', to: 'sessions#new', as: 'login', via: [:get, :post]
match 'logout', to: 'sessions#destroy', as: 'logout', via: [:post]

match 'overview', to: 'pages#overview', as: 'overview', via: [:get]
match 'style-guide', to: 'pages#style_guide', as: 'style_guide', via: [:get]

match 'tags/:tags' => 'tasks#tags', as: 'tags', via: [:get]
match 'untagged' => 'tasks#untagged', as: 'untagged', via: [:get]


resources :sessions
resources :users
resources :comments

resources :tasks, except: [:new] do
  collection { post :sort }
  collection { get :punted }
  collection { post :punt_all_tagged_tasks }
  collection { post :punt_all_tasks }
  collection { put :delete_all_tagged_tasks }
end

root :to => 'pages#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  before_create :add_due_date
  scope :tag, ->(tag) { where("tags like ?", tag) }
  scope :current_user_id, ->(id){ where("user_id = ?", id) }
  scope :punted, ->{ where('due_date > ?', Time.now) }

  # TODO
  # style first, then add validations
  # validates :item, presence: true

  include SimplePosition
  default_scope { order(:position) }

  has_many :comments
  belongs_to :user

private

  def add_due_date
    self.due_date = Time.now
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include ApplicationHelper
  before_filter :authorize, :get_punts


  def index
    @task = Task.new
    @tasks = Task.where(user_id: current_user.id).where( 'due_date <= ? ', Time.now ).order('position')
    @page_title = "#{@tasks.count} #{@tasks.count == 1 ? 'task' : 'tasks'} to destroy!"
    @user = User.find(current_user.id)
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json{ render json: @tasks}
    end
  end

  def tags
    @task = Task.new
    tag_param = "%#{params[:tags]}%"
    @tasks = Task.tag(tag_param).current_user_id(current_user.id)
    @title = params[:tags]
    @comment = Comment.new
  end

  def untagged
    @task = Task.new
    tag_param = ""
    @tasks = Task.tag(tag_param).current_user_id(current_user.id)
    @title = params[:tags]
    @comment = Comment.new
  end

  def punted
    @tasks = Task.current_user_id(current_user.id).punted
  end

  def punt_all_tasks
    tag = request.referrer.split('/').last
    if tag == 'tasks'
      to_punt = Task.where('due_date <= ?', Time.now)
      to_punt.each do |task|
        task.update_attributes(due_date: punt_time )
      end
    else
      tag = request.referrer.split('/').last
      PuntAllTaggedTasksService.call(tag)
    end

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "You punted all #{tag} tags." }
      format.js { render layout: false }
    end
  end

  def punt_all_tagged_tasks
    tag = request.referrer.split('/').last
    PuntAllTaggedTasksService.call(tag)
    redirect_to tasks_path,
      notice: "You punted all #{tag} tags."
  end

  def delete_all_tagged_tasks
    tag = request.referrer.split('/').last
    DeleteAllTaggedTasksService.call(tag)
    redirect_to tasks_path,
      notice: "You deleted all #{tag} tags."
  end


  def show
    begin
      @task       = Task.find(params[:id])

      if current_user.id != @task.user_id
        redirect_to tasks_path, notice: "Not your task to destroy."
      end

      @comment    = Comment.new
      @comments   = Comment.where(task_id: @task).order("created_at DESC")
      @page_title = @task.item
    rescue
      redirect_to tasks_path, notice: "Not your task to destroy."
    end
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
    @page_title = @task.item
  end

  def create
    @task = Task.new(task_params)
    @task.tags = @task.tags.gsub(' ', '')
    if @task.save
      if request.referrer.include?('tags')
        redirect_to tags_path(@task.tags)
      else
        redirect_to tasks_path
      end
    else
      render action: "new"
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    if @task.save
      if request.referrer.include?('tags')
        redirect_to tags_path(@task.tags)
      else
        respond_to do |format|
          format.html { redirect_to tasks_path, notice: "Updated." }
          format.js { render layout: false }
        end
      end
    else
      render :back
      flash[:notice] = "Sorry, something went wrong."
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "destroyed!" }
      format.js   { render layout: false }
    end
  end

  def sort
    params['task-wrapper_task'].each_with_index do |id, index|
      Task.update_all({position: index + 1}, {id: id})
    end
    render nothing: true
  end

private

  def get_punts
    @punts = Task.where('due_date > ?', Time.now).where(user_id: current_user.id)
    @punt_count = @punts.count
  end

  def task_params
    params.require(:task).permit(:completed, :item, :tags, :feature, :position, :due_date, :user_id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  MESSAGES = [
    "You. Are. A. Machine",
    "Agent Smith stands no chance against you",
    "Now go on a hike!",
    "Cheers!",
    "Dang Dude!"
  ]
  def message
    if TaskCounter.count == 0;
      "Let's destroy some tasks."
    else
      MESSAGES[rand(0..MESSAGES.count)]
    end
  end

  def flex_destroy_path(task)
    if task.comments.count > 0
      link_to "#{pluralize(task.comments.count, 'note')}", task_path(task), class: 'link-button-destroy'
    else
      link_to 'Destroy', task, method: :delete, remote: true, class: 'link-button-destroy'
    end
  end

  def flex_punt_path(task)
    if task.due_date <= Time.now
      if params[:action] == 'index'
        link_to 'Punt', task_path(task, task: { due_date: punt_time }), remote: true, class: 'link-button-punt', method: :put
      else
        link_to 'Punt', task_path(task, task: { due_date: punt_time }), class: 'link-button-punt', method: :put
      end
    else
      link_to 'Return', task_path(task, task: { due_date: Time.now }), remote: true, class: 'link-button-punt', method: :put
    end
  end
end

app/views/tasks/_bulk_task_buttons.haml
.bulk-actions
  .ba-punt-all
    = link_to 'Punt All Tasks', punt_all_tasks_tasks_path(task: {due_date: punt_time} ), remote: true,method: :post, class: 'link-button-dark-small'

app/views/tasks/_form_3_entry.haml
.m-task-tag-form
  = form_for @task do |f|
    .task-tag-errors
      - if @task.errors.any?
        #error_explanation
          %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
          %ul
            - @task.errors.full_messages.each do |msg|
              %li= msg

    = f.hidden_field :user_id, value: current_user.id

    .task-tag-task-field
      = f.text_field :item, placeholder: 'Task', id: 'task'
    .task-tag-form-action-items
      .task-tag-tag-field
        = f.text_field :tags, placeholder: "Add a tag"
      .task-tag-save-field
        = f.submit 'Save', class: 'button-save-big'

app/views/tasks/_punted_list.haml
.task-spacer
%h2 Punted
.tasks{ data: { update_url: sort_tasks_url, behavior: 'sortable' } }
  - @tasks.each do |task|
    - if task.due_date >= Time.now
      %section.task-wrapper#task-wrapper{ id: dom_id(task), data: { behavior: 'sortable-item' } }
        = render 'task_2b_row', task: task
        = render 'task_notes', task: task

app/views/tasks/_task_2b_row.haml
.task-list-item
  .task-handle= image_tag('grip.svg')
  .task-text
    .task-item
      %p
        %a{href: "#{task_path(task)}", class: 'link-basic-dark', data: { task: 'item'  }}= "#{task.item}"
    .task-category
      %p
        - task.tags.split(',').each do |tag|
          %a{href: "#{tags_path(tag)}", class: 'link-category'}= "#{tag.gsub(',','')}"
  .task-actions
    .ta-destroy
      %p= flex_destroy_path(task)
    .ta-punt
      %p= flex_punt_path(task)

app/views/tasks/_task_4b_row.haml
.task-list-item
  .task-handle= image_tag('grip.svg')
  .task-text
    .task-item
      %p
        %a{href: "#{task_path(task)}", class: 'link-basic-dark'}= "#{task.item}"
    .task-category
      %p
        - task.tags.split(',').each do |tag|
          %a{href: "#{tags_path(tag)}", class: 'link-category'}= "#{tag.gsub(',','')}"
  .task-actions-4b
    .ta-destroy-4b
      %p= flex_destroy_path(task)
    .ta-punt-4b
      %p= flex_punt_path(task)
    .ta-edit-4b
      %p= link_to "edit", edit_task_path(task), class: 'link-button-edit'
    .ta-return-time-4b
      %p= distance_of_time_in_words_to_now(task.due_date)

app/views/tasks/_task_list.haml
.m-task-mgmt
  .task-tag-punt-all
    = render 'bulk_task_buttons'

.m-task-list
  .tasks#task_list{ data: { update_url: sort_tasks_url, behavior: 'sortable' } }
    - @tasks.each do |task|
      - if task.due_date <= Time.now
        %section.task-wrapper#task-wrapper{ id: dom_id(task), data: { behavior: 'sortable-item' } }
          = render 'task_2b_row', task: task
          = render 'task_notes',  task: task

app/views/tasks/_task_notes.haml
.m-task-note
  = form_for @comment, remote: true do |f|
    = f.hidden_field :task_id, value: task.id
    .tn-field
      .comment-field= f.text_area :entry, rows: "3", placeholder: "Jot some notes."
    .tn-actions.save-btn
      = f.submit 'Save note', class: 'link-button-dark'
      .tn-view-all
        = link_to 'View all notes', task_path(task), class: 'link-button-show-all'

app/views/tasks/edit.html.haml
.summary
  .button-row
    %h1.h1= @task.item
    .two-buttons
      .tb-edit-action
        = link_to 'List', tasks_path, class: 'link-basic-dark'
      .tb-edit-action
        = link_to 'Back', task_path(@task), class: 'link-basic-dark'

    = render 'form_3_entry'

app/views/tasks/index.haml
- flash.each do |key, value|
  .alert{class: "alert-#{key}"}
    = value
.summary.task-page
  = render 'form_3_entry'
  = render 'task_list'

app/views/tasks/punt_all_tasks.js.erb
$('#task_list').hide();

app/views/tasks/punted.haml
.summary.task-page
  .m-task-list
    .tasks#task_list{ data: { update_url: sort_tasks_url, behavior: 'sortable' } }
      - @tasks.each do |task|
        %section.task-wrapper#task-wrapper{ id: dom_id(task), data: { behavior: 'sortable-item' } }
          = render 'task_4b_row', task: task

app/views/tasks/tags.haml
.summary.tag-page
  .tag-header
    %h1= params[:tags]
  .l-primary-content.task-action-bar
    = render 'form_2_entry'
    = render partial: 'task_list'
    = render partial: 'punted_list', tasks: @tasks

app/views/tasks/untagged.haml
.summary.tag-page
  .tag-header
    %h1 Untagged tasks
  .l-primary-content.task-action-bar
    = render 'form_2_entry'
    = render partial: 'task_list'
    = render partial: 'punted_list', tasks: @tasks

app/views/tasks/update.js.erb
$('#task-wrapper_task_<%= @task.id %>').hide();