config/routes.rb
DestroyAllTasks::Application.routes.draw do

resources :profiles, only: [:show, :edit, :update]

match 'signup', to: 'users#new', as: 'signup', via: [:get]
match 'login', to: 'sessions#new', as: 'login', via: [:get, :post]
match 'logout', to: 'sessions#destroy', as: 'logout', via: [:post]

match 'overview', to: 'pages#overview', as: 'overview', via: [:get]
match 'style-guide', to: 'pages#style_guide', as: 'style_guide', via: [:get]

match 'tags/:tags' => 'tasks#tags', as: 'tags', via: [:get]
match 'untagged' => 'tasks#untagged', as: 'untagged', via: [:get]


resources :sessions
resources :users
resources :comments

resources :tasks, except: [:new] do
  collection { post :sort }
  collection { get :punted }
  collection { post :punt_all_tagged_tasks }
  collection { post :punt_all_tasks }
  collection { put :delete_all_tagged_tasks }
end

root :to => 'pages#index'
end

app/views/pages/_navigation.haml
.nav-bar
  .l-constrained
    %section.nav-logo
      %h1 #TODO
      %h2
        =link_to "by wwwooodall", 'http://www.wwwoodall.com'

    %section.nav-links
      %ul
        %li
          - if current_user
            = link_to "Log out", logout_path
          - else
            =link_to "Log In", login_path
        %li
          - if current_user
            = link_to 'Tasks', tasks_path
          - else
            =link_to 'Sign up', signup_path

app/views/pages/index.html.haml
.hero
  .l-constrained
    %h1.hero-caption What do you do <br> when your TODO list <br> is done?

%section.headline
  .l-constrained
    %h1.home-headers Finish each day with a sense of accomplishment
    %hr.full-line-break
    %p Does your current 'list system' help you focus and feel good at the end of the day?
    %p Discover the freedom of living from a single list that has a daily finish line.

%section.overview
  .mac-tasks-image
    =image_tag "mac_overview.gif"
  .overview-copy
    %h1.home-headers One list to rule them all
    %p How many lists do you maintain? There's a better way to get a mental clean slate.
    %p Discover the freedom of living from a single list that has an ending each day.

%section.features
  %h1.home-headers Don't just make a list, do something
  %hr.full-line-break
  .feature-set-a
    %h2 Punt tasks
    %p Can't complete a task today? Punt it! Punted tasks patiently sit for 3 days before returning to your list. Or, manually return a task too.

    %h2 Sort tasks
    %p Sort your list by clicking and dragging

    %h2 Track time
    %p Each task has a timer to keep track of the amount of time you're actually spending <em>during</em> the task time.

  .feature-set-b
    %h2 Tag pages
    %p Add a tag, then click on it to see a filtered list of the same tag name.

    %h2 Highlight a Tasks
    %p Add an '@' ("Lunch @3pm"), or 'zzz' ('zzz later') to highlight the task.

    %h2 Jot notes
    %p Click on a task to see a page dedicated to the task. Take notes, and keep that page open to remind you what you're <em>really</em> supposed to be doing.

%section.show-page
  .show-copy
    %h1.home-headers Focus on the task at hand
    %p
      Click on any task to get it's own page. There, you can track time, add notes, to help you get the task done.
    %p
      Notes are
      %a{ href: "http://daringfireball.net/projects/markdown/basics", class: 'markdown', taget: "_blank"} markdown
      friendly.
  .show-task-image
    =image_tag "mac_show.gif"

%section.signup
  .signup-button-section
    %a{href: "#{signup_path}", class: 'signup-button'} Join for Free
  .signup-copy
    %h1.home-headers Sign up for freedom
    %p
      Start learning what it means to manage your list instead of letting your list manage you.

app/views/pages/overview.haml
.summary
  %h1 <em>Inbox Zero</em> for tasks

  %h2 The point is focus.
  %p We all have storage like dropbox, evernote, google docs, trello, reminders, and more. They are all great and have a purpose. Don't clutter those places up with temporary notes and lists.

  %p Destroy all tasks is not a place to keep memeories, goals, or other things you don't want to check off.

  %h2 How to punt
  %p Lists are great ways to collect our thoughts. Not everything that goes on the list can be handled in a single day. There are tasks we want to do and tasks we have to do.

  %h3 "<em>But It's annoying to have to punt everything repeatedly.</em>"
  %p Punts are a way to look at something. If it's on your list, then it must have some level of importantance. This is a way to constantly remind you to either handle it, or simply declutter your mind by destroying the task.

  %h2 About
  %p I used <a href="http://www.backpackit.com" target="_blank">backpack</a> for years with notes. I loved having my tasks devise agnostic. The one thing I didn't like was that completed tasks would clutter up my work space. I didn't like having to have the noise of either list subjects, or having to double-delete, or confirm delete everything.

app/views/pages/style_guide.haml
.l-constrained.style-guide
  %h1 Header 1
  %h2 Header 2
  %h3 Header 3
  %h4 Header 4
  %h5 Header 5
  %h6 Header 6
  %p Paragraph
  %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %a{href:'#'} This is a link
  %ul
    %li List item
    %li List item
    %li List item
  %td Table Data

%section
  %h1 Wrappers
  .summary
    %h2 .summary
  .listing
    %h2 .listing