config/routes.rb
DestroyAllTasks::Application.routes.draw do

resources :profiles, only: [:show, :edit, :update]

match 'signup', to: 'users#new', as: 'signup', via: [:get]
match 'login', to: 'sessions#new', as: 'login', via: [:get, :post]
match 'logout', to: 'sessions#destroy', as: 'logout', via: [:post]

match 'overview', to: 'pages#overview', as: 'overview', via: [:get]
match 'style-guide', to: 'pages#style_guide', as: 'style_guide', via: [:get]

match 'tags/:tags' => 'tasks#tags', as: 'tags', via: [:get]
match 'untagged' => 'tasks#untagged', as: 'untagged', via: [:get]


resources :sessions
resources :users
resources :comments

resources :tasks, except: [:new] do
  collection { post :sort }
  collection { get :punted }
  collection { post :punt_all_tagged_tasks }
  collection { post :punt_all_tasks }
  collection { put :delete_all_tagged_tasks }
end

root :to => 'pages#index'
end

app/helpers/footer_helper.rb
module FooterHelper
  def footer_nav
    if !!current_user
      render 'layouts/shared/footer/logged_in'
    else
      render 'layouts/shared/footer/public'
    end
  end
end

app/views/layouts/shared/footer/_footer.slim
.l-footer
  .m-footer
    footer
      .footer-list
        = footer_nav

app/views/layouts/shared/footer/_logged_in.slim
.footer-user
  ul
    - @tags.each do |tag|
      li.tag-list-item
        a.link-basic-light href= "#{tags_path(tag)}"= tag
    li.tag-list-item
        a.link-basic-light href= "#{untagged_path}" untagged

app/views/layouts/shared/footer/_public.slim
.footer-public
  ul
    li.tag-list-item
      a.link-basic-light href="#{root_path}" Home
    li.tag-list-item
      a.link-basic-light href="#{signup_path}" Sign Up
    li.tag-list-item
      a.link-basic-light href="#{login_path}" Log In
    li.tag-list-item
      a.link-basic-light href="http://www.wwwoodall.com" target='_blank' by wwwoodall